### ISSUE TITLE
Please update the favicon to this blue one

### ISSUE THREAD

**Issue by frozeman** [lukso-network/docs-website#9]
![lukso_blue_32](https://user-images.githubusercontent.com/232662/130606406-efd47490-a4c6-42f1-9fa9-3933277a9aaa.png)
![lukso_blue_128](https://user-images.githubusercontent.com/232662/130606408-9dc997ba-eace-4524-b18d-9c622c0e9441.png)

**Comment by frozeman** [comment]
@Hugoo pls do

**Comment by Hugoo** [comment]
Should be solved with #10 
Maybe local your cache is not updated yet?

![image](https://user-images.githubusercontent.com/477945/131320640-d1203f3f-0187-4731-ad7e-b5cad2bdd97a.png)
